(function(global){
  'use strict';
  var words={
    zh:{back:'返回基础数据',period:'时间范围',today:'今日',yesterday:'昨日',d7:'近7日',d30:'近30日',custom:'自定义',from:'开始日期',to:'结束日期',apply:'应用',refresh:'刷新数据',reset:'重置筛选',updated:'数据更新时间',range:'当前范围',filter:'筛选维度',all:'全部',people:'人',accounts:'账户',lots:'手',usd:'USD equivalent',
      customerTitle:'用户数据',customerDesc:'查看注册、KYC、开户、首次入金和交易客户的转化与趋势',registered:'注册用户数',kyc:'KYC用户数',opened:'开户用户数',first:'首次入金用户数',tradingUsers:'交易用户数',regMethod:'注册方式',kycLevel:'KYC等级',depositChannel:'首次入金通道',funnel:'用户转化漏斗',trend:'用户趋势',
      fundingTitle:'出入金数据',fundingDesc:'查看成功入金、成功出金、净入金和处理中出金',depositUsers:'入金用户数',deposit:'入金金额',withdrawal:'出金金额',net:'净入金金额',pending:'已申请出金金额',currency:'币种',depositChannel2:'入金通道',withdrawChannel:'出金通道',fundingTrend:'入金 / 出金 / 净入金趋势',channelRank:'通道金额排行',
      tradingTitle:'交易数据',tradingDesc:'查看开仓订单、交易账户及交易手数',orders:'开仓订单数',tradeAccounts:'开仓交易账户数',openLots:'开仓交易手数',category:'交易品类',symbol:'交易品种',tradeTrend:'订单与手数趋势',symbolRank:'品种手数排行'},
    en:{back:'Back to Base Data',period:'Time range',today:'Today',yesterday:'Yesterday',d7:'Last 7 days',d30:'Last 30 days',custom:'Custom',from:'Start date',to:'End date',apply:'Apply',refresh:'Refresh',reset:'Reset filters',updated:'Updated at',range:'Current range',filter:'Dimensions',all:'All',people:'users',accounts:'accounts',lots:'lots',usd:'USD equivalent',
      customerTitle:'User Data',customerDesc:'Registration, KYC, account opening, first deposit and trading conversion',registered:'Registered users',kyc:'KYC users',opened:'Opened account users',first:'First deposit users',tradingUsers:'Trading users',regMethod:'Registration method',kycLevel:'KYC level',depositChannel:'First deposit channel',funnel:'User conversion funnel',trend:'User trend',
      fundingTitle:'Deposit & Withdrawal Data',fundingDesc:'Successful deposits, withdrawals, net deposits and processing withdrawals',depositUsers:'Deposit users',deposit:'Deposit amount',withdrawal:'Withdrawal amount',net:'Net deposit',pending:'Processing withdrawal',currency:'Currency',depositChannel2:'Deposit channel',withdrawChannel:'Withdrawal channel',fundingTrend:'Deposit / Withdrawal / Net trend',channelRank:'Channel amount ranking',
      tradingTitle:'Trading Data',tradingDesc:'Open orders, trading accounts and open lots',orders:'Open orders',tradeAccounts:'Open trading accounts',openLots:'Open lots',category:'Trading category',symbol:'Instrument',tradeTrend:'Orders and lots trend',symbolRank:'Instrument lots ranking'}
  };
  var symbols={all:['all'],forex:['all','EURUSD','GBPUSD','USDJPY'],metals:['all','XAUUSD','XAGUSD'],energy:['all','USOIL','UKOIL'],indices:['all','NAS100','US30'],crypto:['all','BTCUSD','ETHUSD']};
  var st={period:'7d',start:'',end:'',regMethod:'all',kycLevel:'all',depositChannel:'all',currency:'all',withdrawChannel:'all',category:'all',symbol:'all'};
  var lang='zh',type='customer';
  function option(value,label,current){return '<option value="'+value+'"'+(value===current?' selected':'')+'>'+label+'</option>';}
  function select(id,label,opts,current){var h='<label class="dimension-field"><span>'+label+'</span><select id="'+id+'" class="select-control">';opts.forEach(function(o){h+=option(o[0],o[1],current);});return h+'</select></label>';}
  function kpi(icon,label,value,sub){return '<div class="kpi-card"><div class="kpi-icon blue"><i class="fas '+icon+'"></i></div><div class="kpi-content"><div class="kpi-label">'+label+'</div><div class="kpi-value">'+value+'</div><div class="kpi-sub">'+sub+'</div></div></div>';}
  function header(t,s){
    var home=lang==='zh'?'index.html':'dashboard.html',h='<div class="detail-page"><a class="detail-back" href="'+home+'"><i class="fas fa-arrow-left"></i> '+t.back+'</a><div class="detail-hero"><div><h1>'+t[type+'Title']+'</h1><p>'+t[type+'Desc']+'</p></div><span class="live-stamp"><i class="fas fa-circle"></i> '+t.updated+' '+BiData.formatDateTime(s.timestamp)+'</span></div>';
    h+='<section class="overview-filter"><div><label>'+t.period+'</label><div class="date-tabs">';[['today',t.today],['yesterday',t.yesterday],['7d',t.d7],['30d',t.d30],['custom',t.custom]].forEach(function(x){h+='<button class="date-tab '+(st.period===x[0]?'active':'')+'" data-period="'+x[0]+'">'+x[1]+'</button>';});h+='</div></div>';
    if(st.period==='custom')h+='<label class="dimension-field"><span>'+t.from+'</span><input id="custom-start" class="select-control" type="date" value="'+st.start+'"></label><label class="dimension-field"><span>'+t.to+'</span><input id="custom-end" class="select-control" type="date" value="'+st.end+'"></label><button id="apply-date" class="btn-secondary">'+t.apply+'</button>';
    h+='<div class="filter-actions"><button id="reset-detail" class="btn-secondary"><i class="fas fa-rotate-left"></i> '+t.reset+'</button><button id="refresh-detail" class="btn-primary"><i class="fas fa-arrows-rotate"></i> '+t.refresh+'</button></div><div class="filter-summary">'+t.range+': '+BiData.formatDate(s.range.start)+' — '+BiData.formatDate(s.range.end)+'</div></section>';return h;
  }
  function filters(t){
    var common=[['all',t.all],['bank','Bank Transfer'],['card','Card'],['crypto','Crypto'],['local','Local Transfer']],h='<section class="dimension-panel"><strong><i class="fas fa-sliders"></i> '+t.filter+'</strong>';
    if(type==='customer'){h+=select('regMethod',t.regMethod,[['all',t.all],['phone','Phone'],['email','Email']],st.regMethod)+select('kycLevel',t.kycLevel,[['all',t.all],['lv2','Lv2'],['lv3','Lv3']],st.kycLevel)+select('depositChannel',t.depositChannel,common,st.depositChannel);}
    if(type==='funding'){h+=select('currency',t.currency,[['all',t.all],['usd','USD'],['aed','AED']],st.currency)+select('depositChannel',t.depositChannel2,common,st.depositChannel)+select('withdrawChannel',t.withdrawChannel,common,st.withdrawChannel);}
    if(type==='trading'){h+=select('category',t.category,[['all',t.all],['forex','Forex'],['metals','Metals'],['energy','Energy'],['indices','Indices'],['crypto','Crypto']],st.category);var syms=symbols[st.category]||['all'];h+=select('symbol',t.symbol,syms.map(function(x){return[x,x==='all'?t.all:x];}),st.symbol);}
    return h+'</section>';
  }
  function render(){
    var t=words[lang],s=BiData.getSnapshot(st.period,st.start,st.end,st),h=header(t,s)+filters(t);
    if(type==='customer'){var c=s.customer;h+='<div class="kpi-grid">'+kpi('fa-user-plus',t.registered,BiData.formatNumber(c.registeredUsers),t.people)+kpi('fa-user-check',t.kyc,BiData.formatNumber(c.kycUsers),t.people)+kpi('fa-id-card',t.opened,BiData.formatNumber(c.openAccounts),t.people)+kpi('fa-wallet',t.first,BiData.formatNumber(c.firstDepositUsers),t.people)+kpi('fa-chart-line',t.tradingUsers,BiData.formatNumber(c.tradingUsers),t.people)+'</div><div class="detail-chart-grid"><div class="chart-card"><h3>'+t.funnel+'</h3><div id="chart-one" class="chart-container"></div></div><div class="chart-card"><h3>'+t.trend+'</h3><div id="chart-two" class="chart-container"></div></div></div>';}
    if(type==='funding'){var f=s.funding;h+='<div class="kpi-grid">'+kpi('fa-users',t.depositUsers,BiData.formatNumber(f.depositUsers),t.people)+kpi('fa-arrow-down',t.deposit,'$'+BiData.formatNumber(f.depositAmount),t.usd)+kpi('fa-arrow-up',t.withdrawal,'$'+BiData.formatNumber(f.withdrawAmount),t.usd)+kpi('fa-scale-balanced',t.net,'$'+BiData.formatNumber(f.netDeposit),t.usd)+kpi('fa-clock',t.pending,'$'+BiData.formatNumber(f.pendingWithdraw),t.usd)+'</div><div class="detail-chart-grid"><div class="chart-card wide"><h3>'+t.fundingTrend+'</h3><div id="chart-one" class="chart-container"></div></div></div>';}
    if(type==='trading'){var tr=s.trading;h+='<div class="kpi-grid">'+kpi('fa-receipt',t.orders,BiData.formatNumber(tr.openOrders),'orders')+kpi('fa-user-circle',t.tradeAccounts,BiData.formatNumber(tr.tradingAccounts),t.accounts)+kpi('fa-chart-simple',t.openLots,tr.totalLots.toLocaleString('en-US'),t.lots)+'</div><div class="detail-chart-grid"><div class="chart-card wide"><h3>'+t.tradeTrend+'</h3><div id="chart-one" class="chart-container"></div></div></div>';}
    h+='</div>';document.getElementById('page-content').innerHTML=h;draw(s,t);bind();
  }
  function draw(s,t){var labels=s.dates.map(BiData.formatShortDate);if(type==='customer'){BiCharts.renderFunnelChart(document.getElementById('chart-one'),{items:[{label:t.registered,value:s.customer.registeredUsers},{label:t.kyc,value:s.customer.kycUsers},{label:t.opened,value:s.customer.openAccounts},{label:t.first,value:s.customer.firstDepositUsers},{label:t.tradingUsers,value:s.customer.tradingUsers}]});BiCharts.renderMultiLineChart(document.getElementById('chart-two'),{labels:labels,series:[{label:t.registered,data:s.customer.dailyReg,color:'#3B82F6'}]});}if(type==='funding')BiCharts.renderMultiLineChart(document.getElementById('chart-one'),{labels:labels,series:[{label:t.deposit,data:s.funding.dailyDeposit,color:'#10B981'},{label:t.withdrawal,data:s.funding.dailyWithdraw,color:'#EF4444'},{label:t.net,data:s.funding.dailyDeposit.map(function(v,i){return v-s.funding.dailyWithdraw[i];}),color:'#3B82F6'}]});if(type==='trading')BiCharts.renderMultiLineChart(document.getElementById('chart-one'),{labels:labels,series:[{label:t.orders,data:s.trading.dailyOrders,color:'#3B82F6'},{label:t.openLots,data:s.trading.dailyLots,color:'#8B5CF6'}]});}
  function bind(){document.querySelectorAll('[data-period]').forEach(function(x){x.onclick=function(){st.period=this.dataset.period;if(st.period==='custom'&&!st.start){var e=new Date(),b=new Date(Date.now()-6*86400000);st.start=BiData.formatDate(b);st.end=BiData.formatDate(e);}render();};});['regMethod','kycLevel','depositChannel','currency','withdrawChannel','category','symbol'].forEach(function(id){var el=document.getElementById(id);if(el)el.onchange=function(){st[id]=this.value;if(id==='category')st.symbol='all';render();};});var ap=document.getElementById('apply-date');if(ap)ap.onclick=function(){st.start=document.getElementById('custom-start').value;st.end=document.getElementById('custom-end').value;render();};document.getElementById('refresh-detail').onclick=function(){BiData.refresh();render();};document.getElementById('reset-detail').onclick=function(){st={period:'7d',start:'',end:'',regMethod:'all',kycLevel:'all',depositChannel:'all',currency:'all',withdrawChannel:'all',category:'all',symbol:'all'};render();};}
  global.CategoryDetail={init:function(opts){lang=opts.lang;type=opts.type;render();}};
})(window);
